logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20002/eureka/
      
spring:
  profiles:
     active: dev
  rabbitmq:
    host: 192.168.10.171
    port: 5672
    username: spring
    password: spring
